
value:
	gcc -o value value.c
junk:
	gcc -o junk junk.c
hello:
	gcc -o hello hello.c
execc:
	gcc -o execc exec.c

all: value junk hello execc

clean:
	rm -f value junk hello execc JUNK.txt
